// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeatherApp.Models;

#nullable disable

namespace WeatherApp.Migrations
{
    [DbContext(typeof(WeatherContext))]
    [Migration("20260605061719_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WeatherApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValueSql("'user'");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Email" }, "IDX_User_Email");

                    b.HasIndex(new[] { "Id" }, "IDX_User_Id");

                    b.HasIndex(new[] { "Username" }, "IDX_User_Username");

                    b.HasIndex(new[] { "Email" }, "UQ_User_Email")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "UQ_User_Username")
                        .IsUnique();

                    b.ToTable("user");
                });

            modelBuilder.Entity("WeatherApp.Models.Weatherlog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("FeelsLike")
                        .HasPrecision(5)
                        .HasColumnType("decimal(5,2)")
                        .HasComment("Đơn vị: °C");

                    b.Property<sbyte>("Humidity")
                        .HasColumnType("tinyint")
                        .HasComment("Đơn vị: %  (0 - 100)");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("SearchedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("Temperature")
                        .HasPrecision(5)
                        .HasColumnType("decimal(5,2)")
                        .HasComment("Đơn vị: °C");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<decimal>("WindSpeed")
                        .HasPrecision(6)
                        .HasColumnType("decimal(6,2)")
                        .HasComment("Đơn vị: m/s");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Id" }, "IDX_WeatherLog_Id");

                    b.HasIndex(new[] { "UserId" }, "IDX_WeatherLog_UserId");

                    b.ToTable("weatherlog");
                });

            modelBuilder.Entity("WeatherApp.Models.Weatherlog", b =>
                {
                    b.HasOne("WeatherApp.Models.User", "User")
                        .WithMany("Weatherlogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_WeatherLog_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WeatherApp.Models.User", b =>
                {
                    b.Navigation("Weatherlogs");
                });
#pragma warning restore 612, 618
        }
    }
}
